### ISSUE TITLE
Conventions for documentation in the prototype phase

### ISSUE THREAD

**Issue by shlevy** [nix-community/flake.nix#2]
We should settle on expectations for documentation of flakes during the prototyping phase. This should include things like

1. Should description strings be some kind of markup (docbook?)
2. What does the top-level flake documentation look like?
3. How do we give examples, both on a per-definition level and on a flake-wide level?
4. Should we have additional annotations (per flake, flake member, or definition) besides human-oriented description and type annotation?

etc.

**Comment by shlevy** [comment]
@grahamc @tazjin Would love to hear your thoughts

**Comment by shlevy** [comment]
In https://github.com/tazjin/nixdoc/issues/5#issuecomment-433905679, @edolstra wrote:

> I'm not a fan of RST, which has all the "do what I mean" syntax issues common to all markdown-like languages. (E.g. you have to remember what magic number of spaces causes an indented block, what magic characters introduce a section/subsection/italics etc.)

And then on IRC: 

> shlevy> niksnut: Re your comment on RST, does anything viable besides docbook *not* have that issue? If not I'll just switch to docbook :) [09:40]
> niksnut> yes, the one I'm working on ;-)  [09:42]
> niksnut> but it's semantically close to docbook
> shlevy> Is it available for use?
> niksnut> so that may be the best choice (and also what NixOS option descriptions use)
> niksnut> not yet
> shlevy> OK

So going with docbook here

**Comment by tazjin** [comment]
FWIW I think that DocBook (if we're talking about the actual XML representation) is not something that you want to make users write. They probably just won't. This is a balance of technical issues/advantages & usability and I think DocBook is way too far into one direction on that scale.

**Comment by shlevy** [comment]
I'm waffling too much on this already, but convinced to go back to the drawing board

**Comment by shlevy** [comment]
OK, after some further discussion with @tazjin I'm going with:

1. Documentation within nix expressions (e.g. as annotation attributes) defaults to markdown, with a structured escape hatch to docbook
2. External documentation can be either markdown or docbook, by file extension

If need arises we can add other formats (e.g. RST), but with markdown still as the default and likely docbook as the common final target.

**Comment by tazjin** [comment]
This makes sense to me. Most documentation is not going to require a lot of special markup, and giving "power-users" an escape hatch to DocBook (while saying that DocBook is always the documentation output) or similar should be the "best of both worlds".

Either way, all of those formats are structured and if a decision was really made to move to something else later automatic rewriting isn't the hardest thing in the world, as long as *some* convention is in place.

**Comment by edolstra** [comment]
No, I do not want to enshrine Markdown as the blessed documentation language for Nix.

**Comment by shlevy** [comment]
@edolstra So you'd want even per-definition docstrings to be docbook only?

**Comment by shlevy** [comment]
Anyway, for now I'm going to continue under the proposal above. If it's important to do something different even in the prototype phase, I think we should probably set up a call to synchronously hash this out. @edolstra Let me know if you want me to set that up. @grahamc @tazjin and anyone else (not sure how to make this visible pre-RFC...), let me know if you'd want to be included if that happened.

**Comment by tazjin** [comment]
I'd like to be included.
